# Generated by Django 4.0 on 2022-01-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=25)),
                ('tipo', models.CharField(help_text='exemplo: Hi Wall, Multi Split, Cassete', max_length=200)),
                ('tecnologia', models.CharField(help_text='inverter ou convencional', max_length=100)),
                ('capacidade', models.CharField(max_length=100)),
                ('dist_tubulacao', models.IntegerField(help_text='preecha somente o número de metros')),
                ('fluido', models.CharField(max_length=50)),
                ('valor_instal', models.IntegerField(max_length=20)),
            ],
        ),
    ]
