# Generated by Django 4.0 on 2022-01-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacao',
            name='valor_instal',
            field=models.FloatField(max_length=20),
        ),
    ]
