# Generated by Django 4.0 on 2022-01-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalacoes', '0004_instalacao_obs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instalacao',
            options={'verbose_name': 'Instalações'},
        ),
    ]
