# Generated by Django 4.0 on 2022-01-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalacoes', '0005_alter_instalacao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instalacao',
            options={'ordering': ['marca'], 'verbose_name': 'Instalações'},
        ),
    ]
