# Generated by Django 4.0 on 2022-01-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacoes', '0006_alter_instalacao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacao',
            name='total_instal',
            field=models.FloatField(default=0, max_length=20),
        ),
    ]
